# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduling', '0002_auto_20170803_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduling',
            old_name='capacity',
            new_name='capasity',
        ),
    ]
