# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduling', '0004_scheduling_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='capasity',
            field=models.IntegerField(default=1),
        ),
    ]
