# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 13:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccommPrinciple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('description', models.TextField(max_length=2000)),
            ],
        ),
    ]
