# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 15:50
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accomm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('acc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('size', models.IntegerField()),
                ('type', models.TextField(max_length=30)),
                ('location', models.TextField(max_length=2000)),
                ('start_date', models.DateField(default=datetime.datetime.now, null=True)),
                ('end_date', models.DateField(default=datetime.datetime.now, null=True)),
                ('contracted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracted', to=settings.AUTH_USER_MODEL)),
                ('reserved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='accommprinciple',
            name='id',
        ),
        migrations.AlterField(
            model_name='accommprinciple',
            name='rule_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
