# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='size',
            field=models.IntegerField(default=50),
        ),
    ]
