# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomm', '0003_auto_20170730_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='cost',
            field=models.IntegerField(default=200),
        ),
    ]
