# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 13:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomm', '0004_accommodation_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='end_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
