# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 17:48
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='RequestForTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(max_length=1000)),
                ('student_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReserveTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=1000)),
                ('student_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('text', models.TextField(max_length=2000)),
                ('student_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.IntegerField()),
                ('spec', models.TextField(max_length=2000)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='reviewtour',
            name='tour_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tours.Tour'),
        ),
        migrations.AddField(
            model_name='reservetour',
            name='tour_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tours.Tour'),
        ),
        migrations.AddField(
            model_name='requestfortour',
            name='tour_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tours.Tour'),
        ),
        migrations.AddField(
            model_name='comments',
            name='tour_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tours.Tour'),
        ),
    ]
