# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 15:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewtour',
            name='student_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewtour',
            name='tour_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tours.Tour'),
        ),
        migrations.AddField(
            model_name='reservetour',
            name='student_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservetour',
            name='tour_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tours.Tour'),
        ),
        migrations.AddField(
            model_name='requestfortour',
            name='student_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestfortour',
            name='tour_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tours.Tour'),
        ),
    ]
