# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 21:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tours', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='tour_id',
            new_name='tourId',
        ),
        migrations.RenameField(
            model_name='requestfortour',
            old_name='status',
            new_name='textRequest',
        ),
        migrations.RemoveField(
            model_name='requestfortour',
            name='date',
        ),
        migrations.RemoveField(
            model_name='requestfortour',
            name='tour_id',
        ),
        migrations.AddField(
            model_name='comments',
            name='studentId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
