# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0002_auto_20170724_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='capacity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
