# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0003_auto_20170802_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='tourId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tours.Tour'),
        ),
    ]
