# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0003_tour_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=1000)),
                ('tour_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tours.Tour')),
            ],
        ),
    ]
