# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0004_auto_20170802_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='tourId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tours.Tour'),
        ),
    ]
