# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0003_auto_20170803_1630'),
        ('Tours', '0005_auto_20170803_2307'),
    ]

    operations = [
    ]
