# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 15:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0006_merge_20170804_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservetour',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
