# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0007_reservetour_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservetour',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
