# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 20:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
