# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timing', '0002_auto_20170803_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
