# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skill', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='student_id',
        ),
        migrations.AlterField(
            model_name='skill',
            name='coding_skill',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='skill',
            name='presentation_skill',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='skill',
            name='reading_skill',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='skill',
            name='typing_skill',
            field=models.TextField(max_length=2000),
        ),
    ]
