# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skill', '0002_auto_20170801_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='coding_skill',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='skill',
            name='presentation_skill',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='skill',
            name='reading_skill',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='skill',
            name='typing_skill',
            field=models.TextField(),
        ),
    ]
